/**
 * zh overlay for the appstore_modules app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/appstore_modules.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "mod.appstore_registry.key": "签名密钥",
  "mod.appstore_registry.key_note": "轮换密钥不会改变修订号，因此缓存的目录看起来仍然有效。重建是解决办法。",
  "mod.appstore_registry.rebuild": "重建目录",
  "mod.appstore_registry.rebuilt": "已丢弃 {count} 个快照；下次请求将重建。",
  "mod.appstore_registry.revision": "修订号",
  "mod.appstore_registry.revision_note": "目录每次变更时递增；基于旧版本构建的快照会被重建。",
  "mod.appstore_registry.subtitle": "此实例发布什么，以及用什么签名。",
  "mod.appstore_registry.title": "应用注册表",
  "mod.publisher.contact": "联系邮箱",
  "mod.publisher.create_profile": "创建资料",
  "mod.publisher.edit_profile": "编辑资料",
  "mod.publisher.handle": "短名称",
  "mod.publisher.handle_note": "此名称会出现在商店链接中 — 有人链接后更改会破坏这些链接。",
  "mod.publisher.manifest_invalid": "清单不是有效的 JSON。",
  "mod.publisher.no_apps": "尚未注册任何应用。",
  "mod.publisher.no_profile": "该组织尚未注册为发布者。",
  "mod.publisher.no_versions": "未提交版本",
  "mod.publisher.profile": "发布者资料",
  "mod.publisher.status.draft": "草稿",
  "mod.publisher.status.in_review": "审核中",
  "mod.publisher.status.published": "已发布",
  "mod.publisher.status.rejected": "已拒绝",
  "mod.publisher.status.yanked": "已撤回",
  "mod.publisher.submit_note": "清单将进入审核队列。发布由他人决定。",
  "mod.publisher.submit_version": "提交版本",
  "mod.publisher.submitted": "版本 {version} 已进入审核队列。",
  "mod.publisher.subtitle": "注册您组织的应用并提交版本以供审核。",
  "mod.publisher.title": "发布者工作室",
  "mod.publisher.unverified": "未验证",
  "mod.publisher.verified": "已验证",
  "mod.store_review.empty": "没有等待处理的项目。",
  "mod.store_review.no_publishers": "没有已注册的发布者。",
  "mod.store_review.note": "备注",
  "mod.store_review.note_required": "拒绝需要给出发布者可据以修改的理由。",
  "mod.store_review.publish": "发布",
  "mod.store_review.publishers": "发布者",
  "mod.store_review.reject": "拒绝",
  "mod.store_review.requires_platform": "所需平台",
  "mod.store_review.submitted_by": "提交者",
  "mod.store_review.subtitle": "已提交的版本，按到达顺序排列。",
  "mod.store_review.title": "审核队列",
  "mod.store_review.verified": "已验证",
  "mod.store_review.verify": "验证",
};
