/**
 * zh overlay for the billing app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/billing.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "billing.action.create": "创建发票",
  "billing.action.generate": "生成发票",
  "billing.field.amount": "发票金额（₮）",
  "billing.field.contact": "联系人/客户",
  "billing.field.contact_placeholder": "例如：Gerege Systems LLC",
  "billing.field.ebarimt_status": "e-Barimt 状态",
  "billing.field.invoice_number": "发票号",
  "billing.field.payment_status": "付款状态",
  "billing.field.total": "总金额",
  "billing.message.create_failed": "无法创建发票",
  "billing.message.loading": "正在加载发票...",
  "billing.view.create_title": "创建国家费用发票",
  "billing.view.subtitle": "国家费用发票、账单和税务收据",
  "billing.view.title": "账单和 e-Barimt 税务收据",
};
