/**
 * zh overlay for the contacts app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/contacts.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "contacts.action.create": "新联系人",
  "contacts.action.save": "保存联系人",
  "contacts.action.xyp_autofill": "XYP 自动填充",
  "contacts.field.full_name": "全名",
  "contacts.message.create_failed": "无法创建联系人",
  "contacts.message.empty": "尚未创建联系人 — 请添加第一条记录。",
  "contacts.message.load_failed": "无法加载联系人。请检查“联系人”应用是否已安装并启用。",
  "contacts.message.loading": "正在加载联系人...",
  "contacts.message.xyp_failed": "XYP 查询失败",
  "contacts.message.xyp_verified": "XYP 验证公民",
  "contacts.view.create_title": "创建新联系人",
  "contacts.view.subtitle": "管理业务联系人、客户与合作伙伴",
  "contacts.view.title": "联系人目录",
};
