/**
 * zh overlay for the egov app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/egov.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "egov.action.citizen_queried": "公民查询",
  "egov.action.company_queried": "法人查询",
  "egov.action.lookup": "查询",
  "egov.action.open_profile": "打开个人资料",
  "egov.field.address": "地址",
  "egov.field.civil_id": "身份证号",
  "egov.field.company_name": "名称",
  "egov.field.company_reg": "机构登记号",
  "egov.field.endpoint": "地址",
  "egov.field.executive": "法定代表人",
  "egov.field.founding_date": "成立日期",
  "egov.field.full_name": "姓名",
  "egov.field.gender": "性别",
  "egov.field.mode": "模式",
  "egov.field.passport_status": "证件状态",
  "egov.field.rail": "通道",
  "egov.field.reg_number": "登记号",
  "egov.field.status": "状态",
  "egov.field.vat_payer": "增值税纳税人",
  "egov.field.verified": "已验证",
  "egov.field.what": "内容",
  "egov.field.when": "时间",
  "egov.field.who": "操作人",
  "egov.message.empty_history": "本组织尚未进行任何查询。",
  "egov.message.empty_result": "输入登记号即可查询。",
  "egov.message.identities_hint": "您自己的 eID 与 DAN 绑定在个人资料中。它们属于您本人而非本组织，因此不依赖此应用。",
  "egov.message.lookup_failed": "查询失败",
  "egov.message.mock_warning": "处于模拟模式的通道返回的是固定样例数据。其中没有任何内容具有权威性，也不得用于任何政府文件。",
  "egov.mode.live": "已连通",
  "egov.mode.mock": "模拟数据",
  "egov.mode.unconfigured": "未配置",
  "egov.tab.citizen": "公民",
  "egov.tab.company": "法人",
  "egov.view.connections_subtitle": "本部署如何接入国家系统",
  "egov.view.connections_title": "连接",
  "egov.view.history_subtitle": "本组织向国家查询了什么，由谁查询",
  "egov.view.history_title": "查询历史",
  "egov.view.subtitle": "通过 XYP 获取公民与法人的权威数据",
  "egov.view.title": "登记查询",
};
