/**
 * zh overlay for the inventory app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/inventory.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "inventory.action.adjust": "调整库存",
  "inventory.action.confirm_adjustment": "确认调整",
  "inventory.action.create_warehouse": "新建仓库",
  "inventory.action.save_warehouse": "保存仓库",
  "inventory.field.address": "地址",
  "inventory.field.available_quantity": "可用数量",
  "inventory.field.change": "更改",
  "inventory.field.code": "代码",
  "inventory.field.datetime": "日期和时间",
  "inventory.field.product": "产品",
  "inventory.field.reference": "参考/原因",
  "inventory.field.reference_note": "备注",
  "inventory.field.reference_placeholder": "例如：PO-98421 或盘点调整",
  "inventory.field.select_product": "选择产品",
  "inventory.field.select_warehouse": "选择仓库",
  "inventory.field.warehouse": "仓库",
  "inventory.field.warehouse_name": "仓库名称",
  "inventory.message.adjustment_failed": "库存调整失败",
  "inventory.message.adjustment_recorded": "库存调整已记录",
  "inventory.message.empty_movements": "尚未记录任何库存变动。",
  "inventory.message.empty_stock": "尚无库存记录 — 进行一次调整以登记首次入库。",
  "inventory.message.empty_warehouses": "尚未配置仓库 — 请添加第一个库位。",
  "inventory.message.load_failed": "无法加载库存数据。请检查“库存”应用是否已安装并启用。",
  "inventory.message.loading": "正在加载库存数据...",
  "inventory.message.no_address": "未填写地址",
  "inventory.message.warehouse_created": "仓库已创建",
  "inventory.message.warehouse_failed": "无法创建仓库",
  "inventory.view.adjustment": "库存调整",
  "inventory.view.create_warehouse": "创建仓库",
  "inventory.view.movements": "库存移动历史",
  "inventory.view.stock_levels": "实时库存水平",
  "inventory.view.subtitle": "跟踪各仓库的库存水平并记录调整",
  "inventory.view.title": "库存与仓库操作",
  "inventory.view.warehouses": "仓库",
};
