/**
 * zh overlay for the products app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/products.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "products.action.create": "新建产品",
  "products.action.save": "保存产品",
  "products.field.name": "产品名称",
  "products.field.price": "单价",
  "products.field.sku": "SKU 代码",
  "products.field.sku_placeholder": "例如: PROD-001",
  "products.message.create_failed": "无法创建产品",
  "products.message.empty": "尚未添加产品 — 添加第一个产品以建立目录。",
  "products.message.load_failed": "无法加载产品。请检查“产品”应用是否已安装并启用。",
  "products.message.loading": "正在加载产品...",
  "products.view.create_title": "创建新产品",
  "products.view.subtitle": "管理 SKU、产品名称和定价",
  "products.view.title": "产品目录",
};
