/**
 * zh overlay for the reports app.
 *
 * Generated by `npm run i18n:translate -- --locale zh`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/reports.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const zh: Record<string, string> = {
  "reports.action.export_csv": "CSV",
  "reports.action.export_xlsx": "Excel",
  "reports.action.new_schedule": "新建计划",
  "reports.action.run": "运行",
  "reports.action.run_consolidated": "合并",
  "reports.action.schedule": "设定计划",
  "reports.badge.consolidated": "合并",
  "reports.field.cron": "计划 (cron)",
  "reports.field.format": "格式",
  "reports.field.last_run": "上次运行",
  "reports.field.recipients": "收件人",
  "reports.field.report": "报表",
  "reports.field.rows": "行",
  "reports.field.schedule_name": "计划名称",
  "reports.field.total": "合计",
  "reports.hint.consolidated": "与您共享此报表的每个组织的数据。没有共享协议则不显示任何内容 — 设置 → 报表共享。",
  "reports.hint.cron": "分 时 日 月 周。每月 1 日 09:00 为「0 9 1 * *」",
  "reports.hint.recipients": "电子邮件地址，用逗号分隔。",
  "reports.message.delivery_off": "本部署未配置邮件发送，定时报表会生成但不会发送。请设置 REPORT_SMTP_URL。",
  "reports.message.empty": "该期间没有数据。",
  "reports.message.export_failed": "导出失败",
  "reports.message.no_reports": "尚未安装带报表的应用。从应用商店安装后，其报表会显示在此处。",
  "reports.message.no_schedules": "暂无定时报表。",
  "reports.message.run_failed": "报表生成失败",
  "reports.message.running": "正在生成报表…",
  "reports.message.schedule_removed": "计划已删除。",
  "reports.message.schedule_saved": "计划已保存。",
  "reports.message.select": "请从左侧选择一个报表。",
  "reports.section.chart": "图表",
  "reports.section.parameters": "参数",
  "reports.section.reports": "报表",
  "reports.section.schedules": "定时报表",
  "reports.toggle.by_company": "按组织拆分",
  "reports.view.subtitle": "本组织已安装应用的业务报表：运行、图表、导出为 Excel 或 CSV。",
  "reports.view.title": "报表",
};
