/**
 * es overlay for the appstore_modules app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/appstore_modules.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "mod.appstore_registry.key": "Clave de firma",
  "mod.appstore_registry.key_note": "Rotar una clave no mueve la revisión, así que los catálogos en caché siguen pareciendo válidos. Reconstruir es la salida.",
  "mod.appstore_registry.rebuild": "Reconstruir el catálogo",
  "mod.appstore_registry.rebuilt": "Se descartaron {count} instantáneas; la próxima solicitud las reconstruye.",
  "mod.appstore_registry.revision": "Revisión",
  "mod.appstore_registry.revision_note": "Avanza cada vez que cambia el catálogo; una instantánea construida sobre una anterior se reconstruye.",
  "mod.appstore_registry.subtitle": "Lo que publica esta instancia y con qué lo firma.",
  "mod.appstore_registry.title": "Registro de aplicaciones",
  "mod.publisher.contact": "Correo de contacto",
  "mod.publisher.create_profile": "Crear un perfil",
  "mod.publisher.edit_profile": "Editar el perfil",
  "mod.publisher.handle": "Identificador",
  "mod.publisher.handle_note": "Aparece en las URL de la tienda — cambiarlo después de que alguien haya enlazado rompe esos enlaces.",
  "mod.publisher.manifest_invalid": "El manifiesto no es JSON válido.",
  "mod.publisher.no_apps": "Aún no hay aplicaciones registradas.",
  "mod.publisher.no_profile": "Esta organización aún no se ha registrado como editor.",
  "mod.publisher.no_versions": "Sin versiones enviadas",
  "mod.publisher.profile": "Perfil del editor",
  "mod.publisher.status.draft": "borrador",
  "mod.publisher.status.in_review": "en revisión",
  "mod.publisher.status.published": "publicado",
  "mod.publisher.status.rejected": "rechazado",
  "mod.publisher.status.yanked": "retirado",
  "mod.publisher.submit_note": "El manifiesto va a la cola de revisión. La publicación es decisión de otra persona.",
  "mod.publisher.submit_version": "Enviar una versión",
  "mod.publisher.submitted": "La versión {version} está en la cola de revisión.",
  "mod.publisher.subtitle": "Registre las aplicaciones de su organización y envíe versiones para revisión.",
  "mod.publisher.title": "Estudio del editor",
  "mod.publisher.unverified": "No verificado",
  "mod.publisher.verified": "Verificado",
  "mod.store_review.empty": "No hay nada esperando.",
  "mod.store_review.no_publishers": "No hay editores registrados.",
  "mod.store_review.note": "Nota",
  "mod.store_review.note_required": "Un rechazo necesita un motivo sobre el que el editor pueda actuar.",
  "mod.store_review.publish": "Publicar",
  "mod.store_review.publishers": "Editores",
  "mod.store_review.reject": "Rechazar",
  "mod.store_review.requires_platform": "Requiere plataforma",
  "mod.store_review.submitted_by": "Enviado por",
  "mod.store_review.subtitle": "Versiones enviadas, en el orden en que llegaron.",
  "mod.store_review.title": "Cola de revisión",
  "mod.store_review.verified": "Verificado",
  "mod.store_review.verify": "Verificar",
};
