/**
 * es overlay for the billing app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/billing.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "billing.action.create": "Crear factura",
  "billing.action.generate": "Generar factura",
  "billing.field.amount": "Importe de la factura (₮)",
  "billing.field.contact": "Contacto",
  "billing.field.contact_placeholder": "ej. Gerege Systems LLC",
  "billing.field.ebarimt_status": "Estado de e-Barimt",
  "billing.field.invoice_number": "N.º de factura",
  "billing.field.payment_status": "Estado de pago",
  "billing.field.total": "Importe total",
  "billing.message.create_failed": "No se pudo crear la factura",
  "billing.message.loading": "Cargando facturas...",
  "billing.view.create_title": "Crear factura de tasa estatal",
  "billing.view.subtitle": "Facturas de tasas estatales, facturación y recibos de impuestos",
  "billing.view.title": "Facturación pública y recibos de impuestos e-Barimt",
};
