/**
 * es overlay for the contacts app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/contacts.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "contacts.action.create": "Nuevo contacto",
  "contacts.action.save": "Guardar contacto",
  "contacts.action.xyp_autofill": "Autocompletar XYP",
  "contacts.field.full_name": "Nombre completo",
  "contacts.message.create_failed": "No se pudo crear el contacto",
  "contacts.message.empty": "Aún no hay contactos — añada su primer registro.",
  "contacts.message.load_failed": "No se pudieron cargar los contactos. Compruebe que la aplicación Contactos esté instalada y activada.",
  "contacts.message.loading": "Cargando contactos...",
  "contacts.message.xyp_failed": "Error en la consulta XYP",
  "contacts.message.xyp_verified": "Ciudadano verificado por XYP",
  "contacts.view.create_title": "Crear nuevo contacto",
  "contacts.view.subtitle": "Gestione contactos comerciales, clientes y socios",
  "contacts.view.title": "Directorio de contactos",
};
