/**
 * es overlay for the egov app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/egov.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "egov.action.citizen_queried": "Consulta de ciudadano",
  "egov.action.company_queried": "Consulta de persona jurídica",
  "egov.action.lookup": "Consultar",
  "egov.action.open_profile": "Abrir el perfil",
  "egov.field.address": "Dirección",
  "egov.field.civil_id": "Número de documento de identidad",
  "egov.field.company_name": "Nombre",
  "egov.field.company_reg": "Número de registro de la organización",
  "egov.field.endpoint": "Dirección",
  "egov.field.executive": "Representante",
  "egov.field.founding_date": "Fecha de constitución",
  "egov.field.full_name": "Nombre",
  "egov.field.gender": "Sexo",
  "egov.field.mode": "Modo",
  "egov.field.passport_status": "Estado del documento",
  "egov.field.rail": "Canal",
  "egov.field.reg_number": "Número de registro",
  "egov.field.status": "Estado",
  "egov.field.vat_payer": "Sujeto a IVA",
  "egov.field.verified": "Verificado",
  "egov.field.what": "Qué",
  "egov.field.when": "Cuándo",
  "egov.field.who": "Quién",
  "egov.message.empty_history": "Esta organización todavía no ha consultado nada.",
  "egov.message.empty_result": "Introduzca un número de registro para consultarlo.",
  "egov.message.identities_hint": "Sus propios vínculos de eID y DAN están en su perfil. Le pertenecen a usted y no a esta organización, así que no dependen de esta aplicación.",
  "egov.message.lookup_failed": "La consulta ha fallado",
  "egov.message.mock_warning": "Un canal en modo de prueba responde con datos ficticios. Nada de lo que devuelve es oficial, y no debe figurar en ningún documento del Estado.",
  "egov.mode.live": "En servicio",
  "egov.mode.mock": "Datos de prueba",
  "egov.mode.unconfigured": "Sin configurar",
  "egov.tab.citizen": "Ciudadano",
  "egov.tab.company": "Persona jurídica",
  "egov.view.connections_subtitle": "Cómo llega esta instalación a los sistemas del Estado",
  "egov.view.connections_title": "Conexiones",
  "egov.view.history_subtitle": "Qué consultó esta organización al Estado y quién lo consultó",
  "egov.view.history_title": "Historial de consultas",
  "egov.view.subtitle": "Datos oficiales de ciudadanos y personas jurídicas desde XYP",
  "egov.view.title": "Consultas al registro",
};
