/**
 * es overlay for the inventory app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/inventory.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "inventory.action.adjust": "Ajustar stock",
  "inventory.action.confirm_adjustment": "Confirmar ajuste",
  "inventory.action.create_warehouse": "Nuevo almacén",
  "inventory.action.save_warehouse": "Guardar almacén",
  "inventory.field.address": "Dirección",
  "inventory.field.available_quantity": "Cantidad disponible",
  "inventory.field.change": "Cambio",
  "inventory.field.code": "Código",
  "inventory.field.datetime": "Fecha y hora",
  "inventory.field.product": "Producto",
  "inventory.field.reference": "Referencia / Razón",
  "inventory.field.reference_note": "Nota de referencia",
  "inventory.field.reference_placeholder": "ej. PO-98421 o ajuste de recuento físico",
  "inventory.field.select_product": "Seleccione el producto",
  "inventory.field.select_warehouse": "Seleccione el almacén",
  "inventory.field.warehouse": "Almacén",
  "inventory.field.warehouse_name": "Nombre del almacén",
  "inventory.message.adjustment_failed": "Error en el ajuste de stock",
  "inventory.message.adjustment_recorded": "Ajuste de stock registrado",
  "inventory.message.empty_movements": "Aún no se ha registrado ningún movimiento de stock.",
  "inventory.message.empty_stock": "Aún no hay stock registrado — realice un ajuste para registrar la primera entrada.",
  "inventory.message.empty_warehouses": "Aún no hay almacenes — añada su primera ubicación.",
  "inventory.message.load_failed": "No se pudieron cargar los datos de inventario. Compruebe que la aplicación Inventario esté instalada y activada.",
  "inventory.message.loading": "Cargando datos de inventario...",
  "inventory.message.no_address": "Sin dirección indicada",
  "inventory.message.warehouse_created": "Almacén creado",
  "inventory.message.warehouse_failed": "No se pudo crear el almacén",
  "inventory.view.adjustment": "Ajuste de stock",
  "inventory.view.create_warehouse": "Crear almacén",
  "inventory.view.movements": "Historial de movimientos de stock",
  "inventory.view.stock_levels": "Niveles de stock actuales",
  "inventory.view.subtitle": "Controle los niveles de stock en los almacenes y registre los ajustes",
  "inventory.view.title": "Operaciones de inventario y almacén",
  "inventory.view.warehouses": "Almacenes",
};
