/**
 * es overlay for the products app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/products.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "products.action.create": "Nuevo producto",
  "products.action.save": "Guardar producto",
  "products.field.name": "Nombre del producto",
  "products.field.price": "Precio unitario",
  "products.field.sku": "SKU",
  "products.field.sku_placeholder": "ej. PROD-001",
  "products.message.create_failed": "No se pudo crear el producto",
  "products.message.empty": "Aún no hay productos — añada el primero para iniciar el catálogo.",
  "products.message.load_failed": "No se pudieron cargar los productos. Compruebe que la aplicación Productos esté instalada y activada.",
  "products.message.loading": "Cargando productos...",
  "products.view.create_title": "Crear nuevo producto",
  "products.view.subtitle": "Gestionar SKU, nombres de productos y precios",
  "products.view.title": "Catálogo de productos",
};
