/**
 * es overlay for the reports app.
 *
 * Generated by `npm run i18n:translate -- --locale es`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/reports.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const es: Record<string, string> = {
  "reports.action.export_csv": "CSV",
  "reports.action.export_xlsx": "Excel",
  "reports.action.new_schedule": "Nueva programación",
  "reports.action.run": "Ejecutar",
  "reports.action.run_consolidated": "Consolidado",
  "reports.action.schedule": "Programar",
  "reports.badge.consolidated": "Consolidado",
  "reports.field.cron": "Programación (cron)",
  "reports.field.format": "Formato",
  "reports.field.last_run": "Última ejecución",
  "reports.field.recipients": "Destinatarios",
  "reports.field.report": "Informe",
  "reports.field.rows": "filas",
  "reports.field.schedule_name": "Nombre de la programación",
  "reports.field.total": "Total",
  "reports.hint.consolidated": "Las cifras de cada organización que comparte este informe con usted. Sin acuerdo no se muestra nada — Ajustes → Compartir informes.",
  "reports.hint.cron": "Minuto hora día mes día-de-semana. El día 1 del mes a las 09:00: «0 9 1 * *»",
  "reports.hint.recipients": "Direcciones de correo separadas por comas.",
  "reports.message.delivery_off": "Esta instalación no tiene transporte de correo, así que un informe programado se genera pero no se envía. Configure REPORT_SMTP_URL.",
  "reports.message.empty": "No hay datos para este periodo.",
  "reports.message.export_failed": "La exportación falló",
  "reports.message.no_reports": "No hay ninguna aplicación con informes instalada. Instale una desde la tienda y sus informes aparecerán aquí.",
  "reports.message.no_schedules": "No hay informes programados.",
  "reports.message.run_failed": "No se pudo generar el informe",
  "reports.message.running": "Generando el informe…",
  "reports.message.schedule_removed": "La programación se ha eliminado.",
  "reports.message.schedule_saved": "La programación se ha guardado.",
  "reports.message.select": "Elija un informe a la izquierda.",
  "reports.section.chart": "Gráfico",
  "reports.section.parameters": "Parámetros",
  "reports.section.reports": "Informes",
  "reports.section.schedules": "Informes programados",
  "reports.toggle.by_company": "Desglosar por organización",
  "reports.view.subtitle": "Los informes de las aplicaciones instaladas por la organización: ejecución, gráficos, exportación a Excel y CSV.",
  "reports.view.title": "Informes",
};
