/**
 * ar overlay for the appstore_modules app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/appstore_modules.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "mod.appstore_registry.key": "مفتاح التوقيع",
  "mod.appstore_registry.key_note": "تدوير المفتاح لا يحرّك رقم المراجعة، فتبقى الفهارس المخزَّنة تبدو صالحة. إعادة البناء هي المخرج.",
  "mod.appstore_registry.rebuild": "إعادة بناء الفهرس",
  "mod.appstore_registry.rebuilt": "تم إسقاط {count} لقطة؛ الطلب التالي يعيد بناءها.",
  "mod.appstore_registry.revision": "رقم المراجعة",
  "mod.appstore_registry.revision_note": "يتحرك كلما تغيّر الفهرس؛ اللقطة المبنية على رقم أقدم يُعاد بناؤها.",
  "mod.appstore_registry.subtitle": "ما تنشره هذه النسخة، وبماذا توقّعه.",
  "mod.appstore_registry.title": "سجل التطبيقات",
  "mod.publisher.contact": "بريد التواصل",
  "mod.publisher.create_profile": "إنشاء ملف",
  "mod.publisher.edit_profile": "تعديل الملف",
  "mod.publisher.handle": "المعرّف",
  "mod.publisher.handle_note": "يظهر هذا في روابط المتجر — تغييره بعد أن يرتبط به أحد يكسر تلك الروابط.",
  "mod.publisher.manifest_invalid": "الملف ليس JSON صالحًا.",
  "mod.publisher.no_apps": "لا توجد تطبيقات مسجَّلة بعد.",
  "mod.publisher.no_profile": "لم تسجّل هذه المؤسسة كناشر بعد.",
  "mod.publisher.no_versions": "لم تُرسَل إصدارات",
  "mod.publisher.profile": "ملف الناشر",
  "mod.publisher.status.draft": "مسودة",
  "mod.publisher.status.in_review": "قيد المراجعة",
  "mod.publisher.status.published": "منشور",
  "mod.publisher.status.rejected": "مرفوض",
  "mod.publisher.status.yanked": "مسحوب",
  "mod.publisher.submit_note": "يذهب الملف إلى قائمة المراجعة. النشر قرار شخص آخر.",
  "mod.publisher.submit_version": "إرسال إصدار",
  "mod.publisher.submitted": "الإصدار {version} في قائمة المراجعة.",
  "mod.publisher.subtitle": "سجّل تطبيقات مؤسستك وأرسل الإصدارات للمراجعة.",
  "mod.publisher.title": "استوديو الناشر",
  "mod.publisher.unverified": "غير موثَّق",
  "mod.publisher.verified": "موثَّق",
  "mod.store_review.empty": "لا شيء في الانتظار.",
  "mod.store_review.no_publishers": "لا يوجد ناشرون مسجَّلون.",
  "mod.store_review.note": "ملاحظة",
  "mod.store_review.note_required": "الرفض يحتاج سببًا يمكن للناشر التصرف بناءً عليه.",
  "mod.store_review.publish": "نشر",
  "mod.store_review.publishers": "الناشرون",
  "mod.store_review.reject": "رفض",
  "mod.store_review.requires_platform": "يتطلب منصة",
  "mod.store_review.submitted_by": "أرسله",
  "mod.store_review.subtitle": "الإصدارات المُرسَلة، بترتيب وصولها.",
  "mod.store_review.title": "قائمة المراجعة",
  "mod.store_review.verified": "موثَّق",
  "mod.store_review.verify": "توثيق",
};
