/**
 * ar overlay for the billing app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/billing.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "billing.action.create": "إنشاء فاتورة",
  "billing.action.generate": "إصدار الفاتورة",
  "billing.field.amount": "مبلغ الفاتورة (₮)",
  "billing.field.contact": "جهة الاتصال / العميل",
  "billing.field.contact_placeholder": "مثال: Gerege Systems LLC",
  "billing.field.ebarimt_status": "حالة e-Barimt",
  "billing.field.invoice_number": "رقم الفاتورة",
  "billing.field.payment_status": "حالة الدفع",
  "billing.field.total": "المبلغ الإجمالي",
  "billing.message.create_failed": "تعذّر إنشاء الفاتورة",
  "billing.message.loading": "جاري تحميل الفواتير...",
  "billing.view.create_title": "إنشاء فاتورة رسوم الدولة",
  "billing.view.subtitle": "فواتير رسوم الدولة، الفواتير، وإيصالات الضرائب",
  "billing.view.title": "الفواتير العامة وإيصالات ضريبة e-Barimt",
};
