/**
 * ar overlay for the contacts app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/contacts.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "contacts.action.create": "جهة اتصال جديدة",
  "contacts.action.save": "حفظ جهة الاتصال",
  "contacts.action.xyp_autofill": "تعبئة تلقائية لـ XYP",
  "contacts.field.full_name": "الاسم الكامل",
  "contacts.message.create_failed": "تعذّر إنشاء جهة الاتصال",
  "contacts.message.empty": "لا توجد جهات اتصال بعد — أضف أول سجل لك.",
  "contacts.message.load_failed": "تعذّر تحميل جهات الاتصال. تحقّق من تثبيت تطبيق جهات الاتصال وتفعيله.",
  "contacts.message.loading": "جاري تحميل جهات الاتصال...",
  "contacts.message.xyp_failed": "فشل الاستعلام من XYP",
  "contacts.message.xyp_verified": "مواطن تم التحقق منه بواسطة XYP",
  "contacts.view.create_title": "إنشاء جهة اتصال جديدة",
  "contacts.view.subtitle": "إدارة جهات الاتصال التجارية والعملاء والشركاء",
  "contacts.view.title": "دليل جهات الاتصال",
};
