/**
 * ar overlay for the egov app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/egov.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "egov.action.citizen_queried": "استعلام عن مواطن",
  "egov.action.company_queried": "استعلام عن كيان اعتباري",
  "egov.action.lookup": "استعلام",
  "egov.action.open_profile": "فتح الملف الشخصي",
  "egov.field.address": "العنوان",
  "egov.field.civil_id": "رقم الهوية المدنية",
  "egov.field.company_name": "الاسم",
  "egov.field.company_reg": "رقم تسجيل المؤسسة",
  "egov.field.endpoint": "العنوان",
  "egov.field.executive": "المدير التنفيذي",
  "egov.field.founding_date": "تاريخ التأسيس",
  "egov.field.full_name": "الاسم",
  "egov.field.gender": "الجنس",
  "egov.field.mode": "الوضع",
  "egov.field.passport_status": "حالة الهوية",
  "egov.field.rail": "القناة",
  "egov.field.reg_number": "رقم التسجيل",
  "egov.field.status": "الحالة",
  "egov.field.vat_payer": "خاضع لضريبة القيمة المضافة",
  "egov.field.verified": "تم التحقق",
  "egov.field.what": "ماذا",
  "egov.field.when": "متى",
  "egov.field.who": "من",
  "egov.message.empty_history": "لم تستعلم هذه المؤسسة عن أي شيء بعد.",
  "egov.message.empty_result": "أدخل رقم تسجيل للاستعلام عنه.",
  "egov.message.identities_hint": "روابط eID و DAN الخاصة بك موجودة في ملفك الشخصي. هي ملك لك لا للمؤسسة، ولذلك لا تعتمد على هذا التطبيق.",
  "egov.message.lookup_failed": "فشل الاستعلام",
  "egov.message.mock_warning": "القناة في الوضع التجريبي تُجيب من بيانات ثابتة. لا شيء مما تعيده رسمي، ولا يصلح لأي مستند حكومي.",
  "egov.mode.live": "يعمل",
  "egov.mode.mock": "بيانات تجريبية",
  "egov.mode.unconfigured": "غير مُهيأ",
  "egov.tab.citizen": "مواطن",
  "egov.tab.company": "كيان اعتباري",
  "egov.view.connections_subtitle": "كيف يتصل هذا التثبيت بأنظمة الدولة",
  "egov.view.connections_title": "الاتصالات",
  "egov.view.history_subtitle": "ما استعلمت عنه هذه المؤسسة من الدولة، ومن استعلم",
  "egov.view.history_title": "سجل الاستعلامات",
  "egov.view.subtitle": "بيانات رسمية عن الأفراد والكيانات الاعتبارية من XYP",
  "egov.view.title": "استعلامات السجل",
};
