/**
 * ar overlay for the inventory app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/inventory.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "inventory.action.adjust": "تعديل المخزون",
  "inventory.action.confirm_adjustment": "تأكيد التسوية",
  "inventory.action.create_warehouse": "مستودع جديد",
  "inventory.action.save_warehouse": "حفظ المستودع",
  "inventory.field.address": "العنوان",
  "inventory.field.available_quantity": "الكمية المتاحة",
  "inventory.field.change": "التغيير",
  "inventory.field.code": "الرمز",
  "inventory.field.datetime": "التاريخ والوقت",
  "inventory.field.product": "المنتج",
  "inventory.field.reference": "المرجع / السبب",
  "inventory.field.reference_note": "ملاحظة مرجعية",
  "inventory.field.reference_placeholder": "مثال: PO-98421 أو تعديل الجرد الفعلي",
  "inventory.field.select_product": "اختر المنتج",
  "inventory.field.select_warehouse": "اختر المستودع",
  "inventory.field.warehouse": "المستودع",
  "inventory.field.warehouse_name": "اسم المستودع",
  "inventory.message.adjustment_failed": "فشلت تسوية المخزون",
  "inventory.message.adjustment_recorded": "تم تسجيل تسوية المخزون",
  "inventory.message.empty_movements": "لم تُسجَّل أي حركة مخزون بعد.",
  "inventory.message.empty_stock": "لا يوجد مخزون مسجّل بعد — أجرِ تسوية لتسجيل أول إدخال.",
  "inventory.message.empty_warehouses": "لا توجد مستودعات بعد — أضف أول موقع لك.",
  "inventory.message.load_failed": "تعذّر تحميل بيانات المخزون. تحقّق من تثبيت تطبيق المخزون وتفعيله.",
  "inventory.message.loading": "جارٍ تحميل بيانات المخزون...",
  "inventory.message.no_address": "لم يُحدَّد عنوان",
  "inventory.message.warehouse_created": "تم إنشاء المستودع",
  "inventory.message.warehouse_failed": "تعذّر إنشاء المستودع",
  "inventory.view.adjustment": "تعديل المخزون",
  "inventory.view.create_warehouse": "إنشاء مستودع",
  "inventory.view.movements": "سجل حركات المخزون",
  "inventory.view.stock_levels": "مستويات المخزون الحالية",
  "inventory.view.subtitle": "تتبّع مستويات المخزون عبر المستودعات وسجّل التسويات",
  "inventory.view.title": "عمليات المخزون والمستودعات",
  "inventory.view.warehouses": "المستودعات",
};
