/**
 * ar overlay for the products app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/products.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "products.action.create": "منتج جديد",
  "products.action.save": "حفظ المنتج",
  "products.field.name": "اسم المنتج",
  "products.field.price": "سعر الوحدة",
  "products.field.sku": "رمز SKU",
  "products.field.sku_placeholder": "مثال: PROD-001",
  "products.message.create_failed": "تعذّر إنشاء المنتج",
  "products.message.empty": "لا توجد منتجات بعد — أضف أول منتج لبدء الكتالوج.",
  "products.message.load_failed": "تعذّر تحميل المنتجات. تحقّق من تثبيت تطبيق المنتجات وتفعيله.",
  "products.message.loading": "جاري تحميل المنتجات...",
  "products.view.create_title": "إنشاء منتج جديد",
  "products.view.subtitle": "إدارة SKU، أسماء المنتجات، والتسعير",
  "products.view.title": "كتالوج المنتجات",
};
