/**
 * ar overlay for the reports app.
 *
 * Generated by `npm run i18n:translate -- --locale ar`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/reports.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ar: Record<string, string> = {
  "reports.action.export_csv": "CSV",
  "reports.action.export_xlsx": "Excel",
  "reports.action.new_schedule": "جدولة جديدة",
  "reports.action.run": "تشغيل",
  "reports.action.run_consolidated": "موحّد",
  "reports.action.schedule": "جدولة",
  "reports.badge.consolidated": "موحّد",
  "reports.field.cron": "الجدولة (cron)",
  "reports.field.format": "الصيغة",
  "reports.field.last_run": "آخر تشغيل",
  "reports.field.recipients": "المستلمون",
  "reports.field.report": "التقرير",
  "reports.field.rows": "صفوف",
  "reports.field.schedule_name": "اسم الجدولة",
  "reports.field.total": "الإجمالي",
  "reports.hint.consolidated": "أرقام كل مؤسسة تشارك معك هذا التقرير. لا يظهر شيء بدون اتفاق — الإعدادات ← مشاركة التقارير.",
  "reports.hint.cron": "الدقيقة الساعة اليوم الشهر يوم الأسبوع. لأول الشهر الساعة 09:00: «0 9 1 * *»",
  "reports.hint.recipients": "عناوين بريد إلكتروني مفصولة بفواصل.",
  "reports.message.delivery_off": "لا يوجد ناقل بريد مُهيَّأ في هذا التثبيت، لذا يُنتَج التقرير المجدول ولا يُرسَل. اضبط REPORT_SMTP_URL.",
  "reports.message.empty": "لا توجد بيانات لهذه الفترة.",
  "reports.message.export_failed": "فشل التصدير",
  "reports.message.no_reports": "لا يوجد تطبيق بتقارير مثبَّت. ثبّت واحدًا من المتجر وستظهر تقاريره هنا.",
  "reports.message.no_schedules": "لا توجد تقارير مجدولة.",
  "reports.message.run_failed": "تعذّر إنتاج التقرير",
  "reports.message.running": "جارٍ إنتاج التقرير…",
  "reports.message.schedule_removed": "تم حذف الجدولة.",
  "reports.message.schedule_saved": "تم حفظ الجدولة.",
  "reports.message.select": "اختر تقريرًا من اليمين.",
  "reports.section.chart": "الرسم البياني",
  "reports.section.parameters": "المعايير",
  "reports.section.reports": "التقارير",
  "reports.section.schedules": "التقارير المجدولة",
  "reports.toggle.by_company": "التفصيل حسب المؤسسة",
  "reports.view.subtitle": "تقارير التطبيقات التي ثبّتتها المؤسسة: التشغيل والرسوم البيانية والتصدير إلى Excel وCSV.",
  "reports.view.title": "التقارير",
};
