/**
 * ru overlay for the appstore_modules app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/appstore_modules.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "mod.appstore_registry.key": "Ключ подписи",
  "mod.appstore_registry.key_note": "Смена ключа не меняет ревизию, поэтому кэшированные каталоги продолжают выглядеть корректными. Пересборка — выход.",
  "mod.appstore_registry.rebuild": "Пересобрать каталог",
  "mod.appstore_registry.rebuilt": "Отброшено снимков: {count}; следующий запрос пересоберёт их.",
  "mod.appstore_registry.revision": "Ревизия",
  "mod.appstore_registry.revision_note": "Меняется при каждом изменении каталога; снимок, построенный на старой, пересобирается.",
  "mod.appstore_registry.subtitle": "Что публикует этот экземпляр и чем подписывает.",
  "mod.appstore_registry.title": "Реестр приложений",
  "mod.publisher.contact": "Контактная почта",
  "mod.publisher.create_profile": "Создать профиль",
  "mod.publisher.edit_profile": "Изменить профиль",
  "mod.publisher.handle": "Идентификатор",
  "mod.publisher.handle_note": "Он появляется в ссылках магазина — изменение после того, как на вас сослались, ломает эти ссылки.",
  "mod.publisher.manifest_invalid": "Манифест не является корректным JSON.",
  "mod.publisher.no_apps": "Приложения ещё не зарегистрированы.",
  "mod.publisher.no_profile": "Эта организация ещё не зарегистрирована как издатель.",
  "mod.publisher.no_versions": "Версии не отправлены",
  "mod.publisher.profile": "Профиль издателя",
  "mod.publisher.status.draft": "черновик",
  "mod.publisher.status.in_review": "на проверке",
  "mod.publisher.status.published": "опубликовано",
  "mod.publisher.status.rejected": "отклонено",
  "mod.publisher.status.yanked": "отозвано",
  "mod.publisher.submit_note": "Манифест попадает в очередь проверки. Публикация — решение другого.",
  "mod.publisher.submit_version": "Отправить версию",
  "mod.publisher.submitted": "Версия {version} в очереди проверки.",
  "mod.publisher.subtitle": "Регистрируйте приложения вашей организации и отправляйте версии на проверку.",
  "mod.publisher.title": "Студия издателя",
  "mod.publisher.unverified": "Не подтверждён",
  "mod.publisher.verified": "Подтверждён",
  "mod.store_review.empty": "Ничего не ожидает.",
  "mod.store_review.no_publishers": "Издатели не зарегистрированы.",
  "mod.store_review.note": "Примечание",
  "mod.store_review.note_required": "Отклонение требует причины, с которой издатель может что-то сделать.",
  "mod.store_review.publish": "Опубликовать",
  "mod.store_review.publishers": "Издатели",
  "mod.store_review.reject": "Отклонить",
  "mod.store_review.requires_platform": "Требуется платформа",
  "mod.store_review.submitted_by": "Отправил",
  "mod.store_review.subtitle": "Отправленные версии в порядке поступления.",
  "mod.store_review.title": "Очередь проверки",
  "mod.store_review.verified": "Подтверждён",
  "mod.store_review.verify": "Подтвердить",
};
