/**
 * ru overlay for the billing app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/billing.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "billing.action.create": "Создать счет",
  "billing.action.generate": "Сформировать счёт",
  "billing.field.amount": "Сумма счёта (₮)",
  "billing.field.contact": "Контакт / Клиент",
  "billing.field.contact_placeholder": "напр. Gerege Systems LLC",
  "billing.field.ebarimt_status": "Статус e-Barimt",
  "billing.field.invoice_number": "№ счёта",
  "billing.field.payment_status": "Статус оплаты",
  "billing.field.total": "Общая сумма",
  "billing.message.create_failed": "Не удалось создать счёт",
  "billing.message.loading": "Загрузка счетов...",
  "billing.view.create_title": "Создать счет за государственную пошлину",
  "billing.view.subtitle": "Счета за государственные пошлины, счета и налоговые квитанции",
  "billing.view.title": "Счета и налоговые квитанции e-Barimt",
};
