/**
 * ru overlay for the contacts app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/contacts.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "contacts.action.create": "Новый контакт",
  "contacts.action.save": "Сохранить контакт",
  "contacts.action.xyp_autofill": "Автозаполнение XYP",
  "contacts.field.full_name": "Полное имя",
  "contacts.message.create_failed": "Не удалось создать контакт",
  "contacts.message.empty": "Контактов пока нет — добавьте первую запись.",
  "contacts.message.load_failed": "Не удалось загрузить контакты. Проверьте, установлено ли и включено приложение «Контакты».",
  "contacts.message.loading": "Загрузка контактов...",
  "contacts.message.xyp_failed": "Запрос к XYP не выполнен",
  "contacts.message.xyp_verified": "Гражданин, подтвержденный XYP",
  "contacts.view.create_title": "Создать новый контакт",
  "contacts.view.subtitle": "Управление деловыми контактами, клиентами и партнёрами",
  "contacts.view.title": "Справочник контактов",
};
