/**
 * ru overlay for the egov app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/egov.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "egov.action.citizen_queried": "Запрос по гражданину",
  "egov.action.company_queried": "Запрос по юридическому лицу",
  "egov.action.lookup": "Запросить",
  "egov.action.open_profile": "Открыть профиль",
  "egov.field.address": "Адрес",
  "egov.field.civil_id": "Номер удостоверения личности",
  "egov.field.company_name": "Название",
  "egov.field.company_reg": "Регистрационный номер организации",
  "egov.field.endpoint": "Адрес",
  "egov.field.executive": "Руководитель",
  "egov.field.founding_date": "Дата основания",
  "egov.field.full_name": "Имя",
  "egov.field.gender": "Пол",
  "egov.field.mode": "Режим",
  "egov.field.passport_status": "Статус удостоверения",
  "egov.field.rail": "Канал",
  "egov.field.reg_number": "Регистрационный номер",
  "egov.field.status": "Статус",
  "egov.field.vat_payer": "Плательщик НДС",
  "egov.field.verified": "Подтверждено",
  "egov.field.what": "Что",
  "egov.field.when": "Когда",
  "egov.field.who": "Кто",
  "egov.message.empty_history": "Эта организация пока ничего не запрашивала.",
  "egov.message.empty_result": "Введите регистрационный номер, чтобы получить справку.",
  "egov.message.identities_hint": "Ваши собственные привязки eID и DAN находятся в профиле. Они принадлежат вам, а не организации, и поэтому не зависят от этого приложения.",
  "egov.message.lookup_failed": "Запрос не выполнен",
  "egov.message.mock_warning": "Канал в тестовом режиме отвечает заготовленными данными. Ничто из возвращаемого не является официальным и не должно попадать в государственные документы.",
  "egov.mode.live": "Работает",
  "egov.mode.mock": "Тестовые данные",
  "egov.mode.unconfigured": "Не настроено",
  "egov.tab.citizen": "Гражданин",
  "egov.tab.company": "Юридическое лицо",
  "egov.view.connections_subtitle": "Как эта установка соединяется с государственными системами",
  "egov.view.connections_title": "Подключения",
  "egov.view.history_subtitle": "Что эта организация запрашивала у государства и кто запрашивал",
  "egov.view.history_title": "История запросов",
  "egov.view.subtitle": "Официальные данные о гражданах и юридических лицах из XYP",
  "egov.view.title": "Справки из реестра",
};
