/**
 * ru overlay for the inventory app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/inventory.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "inventory.action.adjust": "Корректировать запасы",
  "inventory.action.confirm_adjustment": "Подтвердить корректировку",
  "inventory.action.create_warehouse": "Новый склад",
  "inventory.action.save_warehouse": "Сохранить склад",
  "inventory.field.address": "Адрес",
  "inventory.field.available_quantity": "Доступное количество",
  "inventory.field.change": "Изменение",
  "inventory.field.code": "Код",
  "inventory.field.datetime": "Дата и время",
  "inventory.field.product": "Товар",
  "inventory.field.reference": "Ссылка / Причина",
  "inventory.field.reference_note": "Примечание",
  "inventory.field.reference_placeholder": "напр.: PO-98421 или корректировка по результатам инвентаризации",
  "inventory.field.select_product": "Выберите товар",
  "inventory.field.select_warehouse": "Выберите склад",
  "inventory.field.warehouse": "Склад",
  "inventory.field.warehouse_name": "Название склада",
  "inventory.message.adjustment_failed": "Не удалось выполнить корректировку",
  "inventory.message.adjustment_recorded": "Корректировка запасов записана",
  "inventory.message.empty_movements": "Движений запасов пока не зафиксировано.",
  "inventory.message.empty_stock": "Остатков пока нет — сделайте корректировку, чтобы оприходовать первое поступление.",
  "inventory.message.empty_warehouses": "Складов пока нет — добавьте первую площадку.",
  "inventory.message.load_failed": "Не удалось загрузить данные склада. Проверьте, установлено ли и включено приложение «Склад».",
  "inventory.message.loading": "Загрузка данных о запасах...",
  "inventory.message.no_address": "Адрес не указан",
  "inventory.message.warehouse_created": "Склад создан",
  "inventory.message.warehouse_failed": "Не удалось создать склад",
  "inventory.view.adjustment": "Корректировка запасов",
  "inventory.view.create_warehouse": "Создать склад",
  "inventory.view.movements": "История перемещений запасов",
  "inventory.view.stock_levels": "Текущие остатки",
  "inventory.view.subtitle": "Отслеживайте остатки по складам и фиксируйте корректировки",
  "inventory.view.title": "Операции с запасами и складом",
  "inventory.view.warehouses": "Склады",
};
