/**
 * ru overlay for the products app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/products.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "products.action.create": "Новый продукт",
  "products.action.save": "Сохранить товар",
  "products.field.name": "Название товара",
  "products.field.price": "Цена за единицу",
  "products.field.sku": "SKU код",
  "products.field.sku_placeholder": "например: PROD-001",
  "products.message.create_failed": "Не удалось создать товар",
  "products.message.empty": "Товаров пока нет — добавьте первый, чтобы начать каталог.",
  "products.message.load_failed": "Не удалось загрузить товары. Проверьте, установлено ли и включено приложение «Товары».",
  "products.message.loading": "Загрузка продуктов...",
  "products.view.create_title": "Создать новый товар",
  "products.view.subtitle": "Управление SKU, названиями товаров и ценами",
  "products.view.title": "Каталог товаров",
};
