/**
 * ru overlay for the reports app.
 *
 * Generated by `npm run i18n:translate -- --locale ru`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/reports.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const ru: Record<string, string> = {
  "reports.action.export_csv": "CSV",
  "reports.action.export_xlsx": "Excel",
  "reports.action.new_schedule": "Новое расписание",
  "reports.action.run": "Запустить",
  "reports.action.run_consolidated": "Сводный",
  "reports.action.schedule": "По расписанию",
  "reports.badge.consolidated": "Сводный",
  "reports.field.cron": "Расписание (cron)",
  "reports.field.format": "Формат",
  "reports.field.last_run": "Последний запуск",
  "reports.field.recipients": "Получатели",
  "reports.field.report": "Отчёт",
  "reports.field.rows": "строк",
  "reports.field.schedule_name": "Название расписания",
  "reports.field.total": "Итого",
  "reports.hint.consolidated": "Показатели каждой организации, которая делится с вами этим отчётом. Без соглашения не показывается ничего — Настройки → Обмен отчётами.",
  "reports.hint.cron": "Минута час день месяц день недели. Первое число месяца в 09:00 — «0 9 1 * *»",
  "reports.hint.recipients": "Адреса электронной почты через запятую.",
  "reports.message.delivery_off": "На этой установке не настроена отправка почты: отчёт по расписанию будет сформирован, но не отправлен. Задайте REPORT_SMTP_URL.",
  "reports.message.empty": "За этот период данных нет.",
  "reports.message.export_failed": "Не удалось выполнить экспорт",
  "reports.message.no_reports": "Не установлено ни одного приложения с отчётами. Установите его из магазина, и отчёты появятся здесь.",
  "reports.message.no_schedules": "Расписаний нет.",
  "reports.message.run_failed": "Не удалось сформировать отчёт",
  "reports.message.running": "Формируется отчёт…",
  "reports.message.schedule_removed": "Расписание удалено.",
  "reports.message.schedule_saved": "Расписание сохранено.",
  "reports.message.select": "Выберите отчёт слева.",
  "reports.section.chart": "График",
  "reports.section.parameters": "Параметры",
  "reports.section.reports": "Отчёты",
  "reports.section.schedules": "Отчёты по расписанию",
  "reports.toggle.by_company": "Разбить по организациям",
  "reports.view.subtitle": "Отчёты приложений, установленных в организации. Запуск, графики, экспорт в Excel и CSV.",
  "reports.view.title": "Отчёты",
};
