/**
 * fr overlay for the appstore_modules app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/appstore_modules.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "mod.appstore_registry.key": "Clé de signature",
  "mod.appstore_registry.key_note": "Une rotation de clé ne fait pas avancer la révision : les catalogues en cache continuent de paraître valides. La reconstruction est la sortie.",
  "mod.appstore_registry.rebuild": "Reconstruire le catalogue",
  "mod.appstore_registry.rebuilt": "{count} instantanés supprimés ; la prochaine requête les reconstruit.",
  "mod.appstore_registry.revision": "Révision",
  "mod.appstore_registry.revision_note": "Elle avance à chaque changement du catalogue ; un instantané bâti sur une plus ancienne est reconstruit.",
  "mod.appstore_registry.subtitle": "Ce que cette instance publie, et avec quoi elle le signe.",
  "mod.appstore_registry.title": "Registre des applications",
  "mod.publisher.contact": "Courriel de contact",
  "mod.publisher.create_profile": "Créer un profil",
  "mod.publisher.edit_profile": "Modifier le profil",
  "mod.publisher.handle": "Identifiant",
  "mod.publisher.handle_note": "Il apparaît dans les URL du magasin — le changer après que quelqu'un a créé un lien casse ces liens.",
  "mod.publisher.manifest_invalid": "Le manifeste n'est pas du JSON valide.",
  "mod.publisher.no_apps": "Aucune application enregistrée.",
  "mod.publisher.no_profile": "Cette organisation ne s'est pas encore enregistrée comme éditeur.",
  "mod.publisher.no_versions": "Aucune version soumise",
  "mod.publisher.profile": "Profil de l'éditeur",
  "mod.publisher.status.draft": "brouillon",
  "mod.publisher.status.in_review": "en revue",
  "mod.publisher.status.published": "publié",
  "mod.publisher.status.rejected": "rejeté",
  "mod.publisher.status.yanked": "retiré",
  "mod.publisher.submit_note": "Le manifeste part en file de revue. La publication est la décision d'un autre.",
  "mod.publisher.submit_version": "Soumettre une version",
  "mod.publisher.submitted": "La version {version} est en file de revue.",
  "mod.publisher.subtitle": "Enregistrez les applications de votre organisation et soumettez des versions pour revue.",
  "mod.publisher.title": "Studio de l'éditeur",
  "mod.publisher.unverified": "Non vérifié",
  "mod.publisher.verified": "Vérifié",
  "mod.store_review.empty": "Rien n'attend.",
  "mod.store_review.no_publishers": "Aucun éditeur enregistré.",
  "mod.store_review.note": "Note",
  "mod.store_review.note_required": "Un rejet a besoin d'une raison sur laquelle l'éditeur puisse agir.",
  "mod.store_review.publish": "Publier",
  "mod.store_review.publishers": "Éditeurs",
  "mod.store_review.reject": "Rejeter",
  "mod.store_review.requires_platform": "Nécessite la plateforme",
  "mod.store_review.submitted_by": "Soumis par",
  "mod.store_review.subtitle": "Les versions soumises, dans leur ordre d'arrivée.",
  "mod.store_review.title": "File de revue",
  "mod.store_review.verified": "Vérifié",
  "mod.store_review.verify": "Vérifier",
};
