/**
 * fr overlay for the billing app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/billing.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "billing.action.create": "Créer une facture",
  "billing.action.generate": "Générer la facture",
  "billing.field.amount": "Montant de la facture (₮)",
  "billing.field.contact": "Contact",
  "billing.field.contact_placeholder": "ex. Gerege Systems LLC",
  "billing.field.ebarimt_status": "Statut e-Barimt",
  "billing.field.invoice_number": "N° de facture",
  "billing.field.payment_status": "Statut du paiement",
  "billing.field.total": "Montant total",
  "billing.message.create_failed": "Échec de la création de la facture",
  "billing.message.loading": "Chargement des factures...",
  "billing.view.create_title": "Créer une facture de frais d'État",
  "billing.view.subtitle": "Factures de frais d'État, facturation et reçus fiscaux",
  "billing.view.title": "Facturation publique et reçus fiscaux e-Barimt",
};
