/**
 * fr overlay for the contacts app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/contacts.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "contacts.action.create": "Nouveau contact",
  "contacts.action.save": "Enregistrer le contact",
  "contacts.action.xyp_autofill": "Remplissage automatique XYP",
  "contacts.field.full_name": "Nom complet",
  "contacts.message.create_failed": "Échec de la création du contact",
  "contacts.message.empty": "Aucun contact créé pour l'instant — ajoutez votre premier enregistrement.",
  "contacts.message.load_failed": "Impossible de charger les contacts. Vérifiez que l'application Contacts est installée et activée.",
  "contacts.message.loading": "Chargement des contacts...",
  "contacts.message.xyp_failed": "Échec de la requête XYP",
  "contacts.message.xyp_verified": "Citoyen vérifié XYP",
  "contacts.view.create_title": "Créer un nouveau contact",
  "contacts.view.subtitle": "Gérez les contacts professionnels, les clients et les partenaires",
  "contacts.view.title": "Répertoire des contacts",
};
