/**
 * fr overlay for the egov app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/egov.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "egov.action.citizen_queried": "Consultation citoyen",
  "egov.action.company_queried": "Consultation personne morale",
  "egov.action.lookup": "Consulter",
  "egov.action.open_profile": "Ouvrir le profil",
  "egov.field.address": "Adresse",
  "egov.field.civil_id": "Numéro de carte d'identité",
  "egov.field.company_name": "Nom",
  "egov.field.company_reg": "Numéro d'enregistrement de l'organisation",
  "egov.field.endpoint": "Adresse",
  "egov.field.executive": "Dirigeant",
  "egov.field.founding_date": "Date de création",
  "egov.field.full_name": "Nom",
  "egov.field.gender": "Sexe",
  "egov.field.mode": "Mode",
  "egov.field.passport_status": "Statut du document d'identité",
  "egov.field.rail": "Canal",
  "egov.field.reg_number": "Numéro d'enregistrement",
  "egov.field.status": "Statut",
  "egov.field.vat_payer": "Assujetti à la TVA",
  "egov.field.verified": "Vérifié",
  "egov.field.what": "Quoi",
  "egov.field.when": "Quand",
  "egov.field.who": "Qui",
  "egov.message.empty_history": "Cette organisation n'a encore rien consulté.",
  "egov.message.empty_result": "Saisissez un numéro d'enregistrement pour lancer une consultation.",
  "egov.message.identities_hint": "Vos propres liens eID et DAN se trouvent dans votre profil. Ils vous appartiennent et non à cette organisation, et ne dépendent donc pas de cette application.",
  "egov.message.lookup_failed": "La consultation a échoué",
  "egov.message.mock_warning": "Un canal en mode test répond à partir de données fictives. Rien de ce qu'il renvoie ne fait foi, et rien ne doit figurer sur un document officiel.",
  "egov.mode.live": "En service",
  "egov.mode.mock": "Données de test",
  "egov.mode.unconfigured": "Non configuré",
  "egov.tab.citizen": "Citoyen",
  "egov.tab.company": "Personne morale",
  "egov.view.connections_subtitle": "Comment ce déploiement joint les systèmes de l'État",
  "egov.view.connections_title": "Connexions",
  "egov.view.history_subtitle": "Ce que cette organisation a demandé à l'État, et qui l'a demandé",
  "egov.view.history_title": "Historique des consultations",
  "egov.view.subtitle": "Données officielles sur les citoyens et les personnes morales via XYP",
  "egov.view.title": "Consultations du registre",
};
