/**
 * fr overlay for the inventory app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/inventory.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "inventory.action.adjust": "Ajuster le stock",
  "inventory.action.confirm_adjustment": "Confirmer l'ajustement",
  "inventory.action.create_warehouse": "Nouvel entrepôt",
  "inventory.action.save_warehouse": "Enregistrer l'entrepôt",
  "inventory.field.address": "Adresse",
  "inventory.field.available_quantity": "Quantité disponible",
  "inventory.field.change": "Changement",
  "inventory.field.code": "Code",
  "inventory.field.datetime": "Date et heure",
  "inventory.field.product": "Produit",
  "inventory.field.reference": "Référence / Raison",
  "inventory.field.reference_note": "Note de référence",
  "inventory.field.reference_placeholder": "ex: PO-98421 ou ajustement d'inventaire physique",
  "inventory.field.select_product": "Sélectionner le produit",
  "inventory.field.select_warehouse": "Sélectionner l'entrepôt",
  "inventory.field.warehouse": "Entrepôt",
  "inventory.field.warehouse_name": "Nom de l'entrepôt",
  "inventory.message.adjustment_failed": "Échec de l'ajustement de stock",
  "inventory.message.adjustment_recorded": "Ajustement de stock enregistré",
  "inventory.message.empty_movements": "Aucun mouvement de stock enregistré.",
  "inventory.message.empty_stock": "Aucun stock enregistré — effectuez un ajustement pour saisir votre première entrée.",
  "inventory.message.empty_warehouses": "Aucun entrepôt configuré — ajoutez votre premier site.",
  "inventory.message.load_failed": "Impossible de charger les données d'inventaire. Vérifiez que l'application Inventaire est installée et activée.",
  "inventory.message.loading": "Chargement des données d'inventaire...",
  "inventory.message.no_address": "Aucune adresse indiquée",
  "inventory.message.warehouse_created": "Entrepôt créé",
  "inventory.message.warehouse_failed": "Échec de la création de l'entrepôt",
  "inventory.view.adjustment": "Ajustement de stock",
  "inventory.view.create_warehouse": "Créer un entrepôt",
  "inventory.view.movements": "Historique des mouvements de stock",
  "inventory.view.stock_levels": "Niveaux de stock actuels",
  "inventory.view.subtitle": "Suivez les niveaux de stock des entrepôts et consignez les ajustements",
  "inventory.view.title": "Opérations d'inventaire et d'entrepôt",
  "inventory.view.warehouses": "Entrepôts",
};
