/**
 * fr overlay for the products app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/products.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "products.action.create": "Nouveau produit",
  "products.action.save": "Enregistrer le produit",
  "products.field.name": "Nom du produit",
  "products.field.price": "Prix unitaire",
  "products.field.sku": "Code SKU",
  "products.field.sku_placeholder": "ex. : PROD-001",
  "products.message.create_failed": "Échec de la création du produit",
  "products.message.empty": "Aucun produit ajouté — ajoutez le premier pour démarrer le catalogue.",
  "products.message.load_failed": "Impossible de charger les produits. Vérifiez que l'application Produits est installée et activée.",
  "products.message.loading": "Chargement des produits...",
  "products.view.create_title": "Créer un nouveau produit",
  "products.view.subtitle": "Gérer les SKU, les noms de produits et les prix",
  "products.view.title": "Catalogue de produits",
};
