/**
 * fr overlay for the reports app.
 *
 * Generated by `npm run i18n:translate -- --locale fr`. Hand edits survive:
 * the generator only ever fills in keys that are missing here, so correcting a
 * term is permanent and re-running will not undo it.
 *
 * This file travels with the app. It is loaded by lib/i18n/apps/reports.ts,
 * which hands it to registerDictionary; nothing in the core names it.
 */
export const fr: Record<string, string> = {
  "reports.action.export_csv": "CSV",
  "reports.action.export_xlsx": "Excel",
  "reports.action.new_schedule": "Nouvelle planification",
  "reports.action.run": "Exécuter",
  "reports.action.run_consolidated": "Consolidé",
  "reports.action.schedule": "Planifier",
  "reports.badge.consolidated": "Consolidé",
  "reports.field.cron": "Planification (cron)",
  "reports.field.format": "Format",
  "reports.field.last_run": "Dernière exécution",
  "reports.field.recipients": "Destinataires",
  "reports.field.report": "Rapport",
  "reports.field.rows": "lignes",
  "reports.field.schedule_name": "Nom de la planification",
  "reports.field.total": "Total",
  "reports.hint.consolidated": "Les chiffres de chaque organisation qui partage ce rapport avec vous. Rien n'apparaît sans accord — Paramètres → Partage de rapports.",
  "reports.hint.cron": "Minute heure jour mois jour-de-semaine. Le 1er du mois à 09:00 : « 0 9 1 * * »",
  "reports.hint.recipients": "Adresses e-mail séparées par des virgules.",
  "reports.message.delivery_off": "Aucun transport de courrier n'est configuré : un rapport planifié est produit mais non envoyé. Définissez REPORT_SMTP_URL.",
  "reports.message.empty": "Aucune donnée pour cette période.",
  "reports.message.export_failed": "L'export a échoué",
  "reports.message.no_reports": "Aucune application avec rapports n'est installée. Installez-en une depuis la boutique et ses rapports apparaîtront ici.",
  "reports.message.no_schedules": "Aucun rapport planifié.",
  "reports.message.run_failed": "Le rapport n'a pas pu être produit",
  "reports.message.running": "Production du rapport…",
  "reports.message.schedule_removed": "La planification a été supprimée.",
  "reports.message.schedule_saved": "La planification a été enregistrée.",
  "reports.message.select": "Choisissez un rapport à gauche.",
  "reports.section.chart": "Graphique",
  "reports.section.parameters": "Paramètres",
  "reports.section.reports": "Rapports",
  "reports.section.schedules": "Rapports planifiés",
  "reports.toggle.by_company": "Détailler par organisation",
  "reports.view.subtitle": "Les rapports des applications installées par l'organisation : exécution, graphiques, export Excel et CSV.",
  "reports.view.title": "Rapports",
};
