/*
 * Gerege Nexus
 * Copyright (c) 2026 Gerege Systems Development Team, Gerege Nomadica Foundation
 * Distributed under the Apache 2.0 License.
 */

// Generated by frontend/scripts/generate-icon-map.mjs — do not edit.
//
// Every icon named by a Go menu definition, a catalogue manifest or the shell's
// own search index. Run `npm run icons:generate` after changing any of those;
// CI runs it with --check and fails on a diff.

import type { LucideIcon } from "lucide-react";
import {
  Archive,
  BarChart3,
  Box,
  Boxes,
  Code2,
  FileText,
  Files,
  Grid,
  Inbox,
  KeyRound,
  KeySquare,
  Landmark,
  Layers,
  Link2,
  ListChecks,
  MailCheck,
  Move,
  Network,
  Palette,
  PenTool,
  Route,
  ScrollText,
  Send,
  ServerCog,
  Settings,
  Share2,
  ShieldCheck,
  Users,
  Workflow,
} from "lucide-react";

export const ICONS: Record<string, LucideIcon> = {
  "archive": Archive,
  "bar-chart-3": BarChart3,
  "box": Box,
  "boxes": Boxes,
  "code-2": Code2,
  "file-text": FileText,
  "files": Files,
  "grid": Grid,
  "inbox": Inbox,
  "key-round": KeyRound,
  "key-square": KeySquare,
  "landmark": Landmark,
  "layers": Layers,
  "link-2": Link2,
  "list-checks": ListChecks,
  "mail-check": MailCheck,
  "move": Move,
  "network": Network,
  "palette": Palette,
  "pen-tool": PenTool,
  "route": Route,
  "scroll-text": ScrollText,
  "send": Send,
  "server-cog": ServerCog,
  "settings": Settings,
  "share-2": Share2,
  "shield-check": ShieldCheck,
  "users": Users,
  "workflow": Workflow,
};
